# -*- coding: utf-8 -*-
"""Deleting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IxKo0P2iAMofrpRWTo2KpMdQ9Xf3xthm
"""

from flask import Flask, request, render_template_string
import pyodbc


app = Flask(__name__)

# Database connection function
def get_connection():
    return pyodbc.connect(
        'DRIVER={SQL Server};'
        'Server=LAPTOP-QOK8SQ4M\\MSSQLSERVER1;'
        'Database=ChessApp;'
        'Trusted_Connection=yes;'
    )

@app.route("/delete_user", methods=["GET", "POST"])
def delete_user():
    msg = ""
    if request.method == "POST":
        try:
            conn = get_connection()
            cur = conn.cursor()
            sql = "DELETE FROM Users WHERE user_id = ?"
            cur.execute(sql, (int(request.form["user_id"]),))
            conn.commit()
            msg = "✅ User deleted."
        except Exception as e:
            msg = f"❌ Error: {e}"

    return render_template_string("""
    <h2>Delete User</h2>
    <form method="post">
      User ID to Delete: <input name="user_id"><br>
      <button type="submit">Delete</button>
    </form>
    <p>{{ msg }}</p>
    <a href='/'>← Home</a>
    """, msg=msg)
@app.route("/delete_game", methods=["GET", "POST"])
def delete_game():
    msg = ""
    if request.method == "POST":
        try:
            conn = get_connection()
            cur = conn.cursor()
            sql = "DELETE FROM Games WHERE game_id = ?"
            cur.execute(sql, (int(request.form["game_id"]),))
            conn.commit()
            msg = "✅ Game deleted."
        except Exception as e:
            msg = f"❌ Error: {e}"

    return render_template_string("""
    <h2>Delete Game</h2>
    <form method="post">
      Game ID to Delete: <input name="game_id"><br>
      <button type="submit">Delete</button>
    </form>
    <p>{{ msg }}</p>
    <a href='/'>← Home</a>
    """, msg=msg)
@app.route("/delete_ai_game", methods=["GET", "POST"])
def delete_ai_game():
    msg = ""
    if request.method == "POST":
        try:
            conn = get_connection()
            cur = conn.cursor()
            sql = "DELETE FROM AI_Games WHERE ai_game_id = ?"
            cur.execute(sql, (int(request.form["ai_game_id"]),))
            conn.commit()
            msg = "✅ AI Game deleted."
        except Exception as e:
            msg = f"❌ Error: {e}"

    return render_template_string("""
    <h2>Delete AI Game</h2>
    <form method="post">
      AI Game ID to Delete: <input name="ai_game_id"><br>
      <button type="submit">Delete</button>
    </form>
    <p>{{ msg }}</p>
    <a href='/'>← Home</a>
    """, msg=msg)
@app.route("/delete_leaderboard", methods=["GET", "POST"])
def delete_leaderboard():
    msg = ""
    if request.method == "POST":
        try:
            conn = get_connection()
            cur = conn.cursor()
            sql = "DELETE FROM Leaderboard WHERE rank = ?"
            cur.execute(sql, (int(request.form["rank"]),))
            conn.commit()
            msg = "✅ Leaderboard entry deleted."
        except Exception as e:
            msg = f"❌ Error: {e}"

    return render_template_string("""
    <h2>Delete Leaderboard Entry</h2>
    <form method="post">
      Rank ID to Delete: <input name="rank"><br>
      <button type="submit">Delete</button>
    </form>
    <p>{{ msg }}</p>
    <a href='/'>← Home</a>
    """, msg=msg)

@app.route("/")
def home():
    return render_template_string("""
    <h2>Welcome to ChessApp Portal</h2>
    <ul>
        <li><a href="/analytics">Go to Analytics</a></li>
        <li><a href="/insert_user">Insert User</a></li>
        <li><a href="/update_user">Update User</a></li>
        <li><a href="/delete_user">Delete User</a></li>
    </ul>
    """)

app.run(port=5000)