# -*- coding: utf-8 -*-
"""Inserting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Toysa6GRiPOwJ_O6XtGELcEsQb4RsApM

Inserting
"""

from flask import Flask, request, render_template_string
import pyodbc


app = Flask(__name__)

# Database connection function
def get_connection():
    return pyodbc.connect(
        'DRIVER={SQL Server};'
        'Server=LAPTOP-QOK8SQ4M\\MSSQLSERVER1;'
        'Database=ChessApp;'
        'Trusted_Connection=yes;'
    )

### === USERS === ###
@app.route("/", methods=["GET", "POST"])
def insert_user():
    msg = ""
    if request.method == "POST":
        try:
            conn = get_connection()
            cur = conn.cursor()
            sql = """INSERT INTO Users (username, email, password_hash, elo_rating)
                     VALUES (?, ?, ?, ?)"""
            cur.execute(sql, (
                request.form["username"],
                request.form["email"],
                request.form["password_hash"],
                int(request.form["elo_rating"])
            ))
            conn.commit()
            msg = f"✅ User '{request.form['username']}' inserted."
        except Exception as e:
            msg = f"❌ Error: {e}"

    return render_template_string("""
    <h2>Insert into Users</h2>
    <form method="post">
      Username: <input name="username"><br>
      Email: <input name="email"><br>
      Password Hash: <input name="password_hash"><br>
      Elo Rating: <input name="elo_rating"><br>
      <button type="submit">Insert</button>
    </form>
    <p>{{ msg }}</p>
    <a href='/games'>Insert Game</a> | <a href='/ai_games'>Insert AI Game</a> | <a href='/leaderboard'>Insert Leaderboard</a>
    """, msg=msg)

### === GAMES === ###
@app.route("/games", methods=["GET", "POST"])
def insert_game():
    msg = ""
    if request.method == "POST":
        try:
            conn = get_connection()
            cur = conn.cursor()
            sql = """INSERT INTO Games (player1_id, player2_id, winner_id, game_date, game_type)
                     VALUES (?, ?, ?, ?, ?)"""
            cur.execute(sql, (
                int(request.form["player1_id"]),
                int(request.form["player2_id"]),
                int(request.form["winner_id"]) if request.form["winner_id"] else None,
                request.form["game_date"],
                request.form["game_type"]
            ))
            conn.commit()
            msg = "✅ Game inserted."
        except Exception as e:
            msg = f"❌ Error: {e}"

    return render_template_string("""
    <h2>Insert into Games</h2>
    <form method="post">
      Player 1 ID: <input name="player1_id"><br>
      Player 2 ID: <input name="player2_id"><br>
      Winner ID (or leave blank for draw): <input name="winner_id"><br>
      Game Date (YYYY-MM-DD HH:MM): <input name="game_date"><br>
      Game Type (PVP or AI): <input name="game_type"><br>
      <button type="submit">Insert</button>
    </form>
    <p>{{ msg }}</p>
    <a href='/'>Insert User</a> | <a href='/ai_games'>Insert AI Game</a> | <a href='/leaderboard'>Insert Leaderboard</a>
    """, msg=msg)

### === AI GAMES === ###
@app.route("/ai_games", methods=["GET", "POST"])
def insert_ai_game():
    msg = ""
    if request.method == "POST":
        try:
            conn = get_connection()
            cur = conn.cursor()
            sql = """INSERT INTO AI_Games (user_id, ai_difficulty, result, game_date)
                     VALUES (?, ?, ?, ?)"""
            cur.execute(sql, (
                int(request.form["user_id"]),
                request.form["ai_difficulty"],
                request.form["result"],
                request.form["game_date"]
            ))
            conn.commit()
            msg = "✅ AI Game inserted."
        except Exception as e:
            msg = f"❌ Error: {e}"

    return render_template_string("""
    <h2>Insert into AI Games</h2>
    <form method="post">
      User ID: <input name="user_id"><br>
      AI Difficulty (Easy, Medium, Hard, Expert): <input name="ai_difficulty"><br>
      Result (Win, Loss, Draw): <input name="result"><br>
      Game Date (YYYY-MM-DD HH:MM): <input name="game_date"><br>
      <button type="submit">Insert</button>
    </form>
    <p>{{ msg }}</p>
    <a href='/'>Insert User</a> | <a href='/games'>Insert Game</a> | <a href='/leaderboard'>Insert Leaderboard</a>
    """, msg=msg)

### === LEADERBOARD === ###
@app.route("/leaderboard", methods=["GET", "POST"])
def insert_leaderboard():
    msg = ""
    if request.method == "POST":
        try:
            conn = get_connection()
            cur = conn.cursor()
            sql = """INSERT INTO Leaderboard (user_id, elo_rating, last_game_date)
                     VALUES (?, ?, ?)"""
            cur.execute(sql, (
                int(request.form["user_id"]),
                int(request.form["elo_rating"]),
                request.form["last_game_date"]
            ))
            conn.commit()
            msg = "✅ Leaderboard record inserted."
        except Exception as e:
            msg = f"❌ Error: {e}"

    return render_template_string("""
    <h2>Insert into Leaderboard</h2>
    <form method="post">
      User ID: <input name="user_id"><br>
      Elo Rating: <input name="elo_rating"><br>
      Last Game Date (YYYY-MM-DD HH:MM): <input name="last_game_date"><br>
      <button type="submit">Insert</button>
    </form>
    <p>{{ msg }}</p>
    <a href='/'>Insert User</a> | <a href='/games'>Insert Game</a> | <a href='/ai_games'>Insert AI Game</a>
    """, msg=msg)

@app.route("/")
def home():
    return render_template_string("""
    <h2>Welcome to ChessApp Portal</h2>
    <ul>
        <li><a href="/analytics">Go to Analytics</a></li>
        <li><a href="/insert_user">Insert User</a></li>
        <li><a href="/update_user">Update User</a></li>
        <li><a href="/delete_user">Delete User</a></li>
    </ul>
    """)

app.run(port=5000)

!pkill -f ngrok