# -*- coding: utf-8 -*-
"""Creating.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-GRfAhL9O_OlZ-zhvlioBcVWgBDm7I6

Creating
"""

from flask import Flask, request, render_template_string

import pyodbc

app = Flask(__name__)

html = """
<h2>Create a New Table in ChessApp</h2>
<form method="post">
  Table Name: <input name="table_name"><br><br>

  Column 1 Name: <input name="col1_name">
  Type:
  <select name="col1_type">
    <option value="VARCHAR(50)">VARCHAR(50)</option>
    <option value="INT">INT</option>
  </select><br><br>

  Column 2 Name: <input name="col2_name">
  Type:
  <select name="col2_type">
    <option value="VARCHAR(50)">VARCHAR(50)</option>
    <option value="INT">INT</option>
  </select><br><br>

  Column 3 Name: <input name="col3_name">
  Type:
  <select name="col3_type">
    <option value="VARCHAR(50)">VARCHAR(50)</option>
    <option value="INT">INT</option>
  </select><br><br>

  <button type="submit">Create Table</button>
</form>
<p>{{ msg }}</p>
"""

@app.route("/", methods=["GET", "POST"])
def create_table():
    msg = ""
    if request.method == "POST":
        try:
            # Grab form values
            table = request.form["table_name"]
            col1 = request.form["col1_name"]
            type1 = request.form["col1_type"]
            col2 = request.form["col2_name"]
            type2 = request.form["col2_type"]
            col3 = request.form["col3_name"]
            type3 = request.form["col3_type"]

            # Connect to SQL Server
            conn = pyodbc.connect(
                'DRIVER={SQL Server};'
                'Server=LAPTOP-QOK8SQ4M\\MSSQLSERVER1;'
                'Database=ChessApp;'
                'Trusted_Connection=yes;'
            )
            conn.autocommit = True

            # Build SQL string
            sql = f"""
            CREATE TABLE {table} (
                {col1} {type1},
                {col2} {type2},
                {col3} {type3}
            )
            """
            conn.execute(sql)
            msg = f"✅ Table '{table}' created successfully!"

        except Exception as e:
            msg = f"❌ Error: {str(e)}"

    return render_template_string(html, msg=msg)

app.run(port=5000)